#pragma once

#include "../occur/all.hh"

#include "./cut.hh"
#include "./dilate.hh"
#include "./dilated.hh"
#include "./discard.hh"
#include "./discarded.hh"
#include "./dot.hh"
#include "./dots.hh"
#include "./either.hh"
#include "./identity.hh"
#include "./imagine.hh"
#include "./magnum.hh"
#include "./near.hh"
#include "./nearing.hh"
//nclude "./phasor.hh"
#include "./power.hh"
#include "./root.hh"
#include "./roots.hh"
#include "./signum.hh"
#include "./square.hh"
#include "./term.hh"
#include "./termial.hh"
#include "./wrap.hh"
