name: Conan Create

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create:
    strategy:
      matrix:
        bt: [Debug] #, Release]
        os: [macOS, Ubuntu] #, Windows]
    
    runs-on: ${{matrix.os}}-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: synthetic-methods/xtal
        path:       test_dependencies/xtal

    - run:  brew install conan
      if:   ${{ matrix.os == 'macOS' }}

    - run:  pip3 install wheel setuptools; pip3 install conan --upgrade
      if:   ${{ matrix.os != 'macOS' }}

    - run:  conan remote update conancenter --url="https://center2.conan.io"
    - run:  conan config install ${{github.workspace}}/.conan2
    - run:  conan export ${{github.workspace}}/test_dependencies/xtal
    - run:  conan create ${{github.workspace}} --build=missing -s build_type=${{matrix.bt}} --profile:all=${{matrix.os}} -o "test_package/*:benchmark=True"
